log:
  level: DEBUG
entrypoints:
  web:
    address: :80
providers:
  file:
    filename: /dynamic.yaml
experimental:
  plugins:
    htransformation:
      modulename: "github.com/tomMoulard/htransformation"
      version: "v0.3.0"
